In [27]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
my_array=np.array([2,5,6,8])
my_array

array([2, 5, 6, 8])

In [4]:
my_array1=np.array(["elo","marx","abello"])
my_array1

array(['elo', 'marx', 'abello'], dtype='<U6')

In [5]:
my_array.dtype

dtype('int64')

In [6]:
my_array1.dtype

dtype('<U6')

In [7]:
my_list=["elo","marx","abello"]

In [8]:
my_second_array=np.array(my_list)
my_second_array

array(['elo', 'marx', 'abello'], dtype='<U6')

In [9]:
extended_array=np.append(my_array,[10,8])
extended_array

array([ 2,  5,  6,  8, 10,  8])

In [10]:
sorted_array=np.sort(extended_array)
sorted_array

array([ 2,  5,  6,  8,  8, 10])

In [11]:
ds_array=np.flip(extended_array)
ds_array

array([ 8, 10,  8,  6,  5,  2])

In [12]:
seq=np.arange(2,10,2)
seq

array([2, 4, 6, 8])

In [13]:
seq2=np.linspace(2,10,3)
seq2

array([ 2.,  6., 10.])

In [14]:
extended_array

array([ 2,  5,  6,  8, 10,  8])

In [15]:
descending_array=np.sort(extended_array)
descending_array

array([ 2,  5,  6,  8,  8, 10])

In [16]:
descending_array=np.sort(extended_array)[:0:-1]
descending_array

array([10,  8,  8,  6,  5])

In [17]:
extended_array[1::2]

array([5, 8, 8])

In [18]:
my_array

array([2, 5, 6, 8])

In [19]:

my_second_array=np.array([16,20,5,1])
my_second_array

array([16, 20,  5,  1])

In [20]:
my_second_array+2

array([18, 22,  7,  3])

In [21]:
my_second_array*2

array([32, 40, 10,  2])

In [22]:
my_array

array([2, 5, 6, 8])

In [23]:
my_second_array+my_array

array([18, 25, 11,  9])

In [28]:
my_third=np.array([32, 40, 10,  2,8,6])
my_third

array([32, 40, 10,  2,  8,  6])

In [29]:
my_array+my_third

ValueError: operands could not be broadcast together with shapes (4,) (6,) 

In [ ]:
my_reshape=my_third.reshape(3,2)

In [ ]:
my_reshape

In [ ]:
my_four=np.array([5,8])
my_four

In [ ]:
my_reshape+my_four

In [ ]:
my_five=np.array([my_four,my_four,my_four])
my_five

In [ ]:
my_reshape+my_five

In [ ]:
my_reshape+my_four

In [ ]:
my_four

In [ ]:
my_reshape

In [ ]:
my_reshape*my_four

In [ ]:
arr1 = np.array([[1,2,3],[4,5,6]])

In [ ]:
arr1


In [ ]:
arr2 = np.array([[7,8,9,10],[11,12,13,14],[15,16,17,18]])

In [ ]:
arr2

In [ ]:
np.dot(arr1,arr2)

In [ ]:
my_ones=np.ones(3)

In [ ]:
my_ones

In [ ]:
my_ones=np.ones((3,3))

In [ ]:
my_ones

In [ ]:
my_zero=np.zeros(3)
my_zero

In [ ]:
my_zero=np.zeros((3,3))
my_zero

In [ ]:
my_zero[0][0]=1

In [ ]:
my_zero

In [ ]:
my_zero[1][1]=1
my_zero[2][2]=1


In [ ]:
my_zero

In [ ]:
my_eyes=np.eye(3)

In [ ]:
my_eyes

In [ ]:
idf=np.identity(3)

In [ ]:
idf

In [ ]:
a =idf[1]

In [ ]:
a

In [ ]:
a.shape


In [ ]:
b =np.array([[0,1,0]])

In [ ]:
b


In [ ]:
b.shape

In [ ]:
a

In [ ]:
a.T

In [ ]:
b.T.shape

In [ ]:
b

In [ ]:
b.ndim

In [ ]:
a.ndim

In [ ]:
a.size

In [ ]:
b.size

In [ ]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[-1,-3],[1,4],[-2,6
                               
                               
                               ]])

In [ ]:
arr1.dot(arr2
        )

In [ ]:
 y = a*X + b

In [ ]:
X=2+np.random.rand(1000,1) #generer des valeurs aléatoire
y=3+4*X+np.random.randn(1000,1)

In [ ]:
X

In [ ]:
y

In [ ]:
plt.scatter(X,y)

In [ ]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

In [ ]:
result=np.c_[arr1,arr2]

In [ ]:
result

In [ ]:
X_b=np.c_[np.ones((1000,1)),X]
X_b

In [ ]:
theta_best=np.linalg.inv(X_b.T.dot(X_b)).dot(X_b.T).dot(y)
theta_best

In [ ]:
X_new=np.array([[0],[2]])
X_new_b=np.c_[np.ones((2,1)),X_new]

In [ ]:
y_pred=X_new_b.dot(theta_best)

In [ ]:
y_pred

In [ ]:
plt.plot(X_new,y_pred,"r-")
plt.plot(X,y,"b.")
